# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0b52270de4c54cd070450ed113dabc05135cc675fe4e2c3901cf63b1dfbb16ac8f1890a089474826848f6f6cf7aa7b32151e8b43196c8230ab90c9abc2cd4af

test:
  secret_key_base: f0b942d6fc7893df8756b3cedb0063afe61b132ff6428b977458022cac8dd96e5a0403bf6e5cd874fc0e01ff0169e3de2ebe3861ef3c3bad934267744cbe71b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
